CREATE TABLE TOTAL_PAGEVIEW_BY_PAGEGROUP_HOPPING_WINDOW AS
SELECT 
  page_group,
  COUNT(*) AS total_view,
  TIMESTAMPTOSTRING(WINDOWSTART, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS window_start,
  TIMESTAMPTOSTRING(WINDOWEND, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS window_end
FROM EXTENTED_PAGEVIEWS_STREAM
WINDOW HOPPING (SIZE 1 HOUR, ADVANCE BY 30 MINUTES)
GROUP BY page_group
EMIT CHANGES;