CREATE TABLE TOTAL_PAGEVIEW_BY_PAGEGROUP_TUMBLING_WINDOW AS
SELECT 
  page_group as key,
  CAST(page_group AS STRING) AS page_group,
  COUNT(*) AS total_view,
  TIMESTAMPTOSTRING(WINDOWSTART, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS window_start,
  TIMESTAMPTOSTRING(WINDOWEND, 'yyyy-MM-dd HH:mm:ss', 'UTC') AS window_end
FROM EXTENTED_PAGEVIEWS_STREAM
WINDOW TUMBLING (SIZE 1 HOUR)
GROUP BY page_group
EMIT CHANGES;
